### ISSUE TITLE
Handle ROS 2 distro change between builds

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#135]
**Is your feature request related to a problem? Please describe.**
Currently, no targets would be built in the following scenario:
1) The user sourced ROS 2 Galactic.
2) The project was built with the Gem 
3) The user sourced ROS 2 Humble
4) Built command is ran.

The ENV variable ROS_DISTRO is not considered a dependency, but it should.

**Comment by hultonha** [comment]
Tagging @lumberyard-employee-dm and @lawsonamzn who may be able to advice on this.

The key problem is when switching the ROS_DISTRO, the generated build files won't be able to detect this so a full rebuild will be required.

One solution may be to create a target the always needs to be built, but this hasn't been implemented. We'd be very grateful for any suggestions/advice. Thanks!

**Comment by lawsonamzn** [comment]
I think there's actually 2 problems hidden here.
1. CMake itself assumes that if the user messes with the environment, the user is smart enough to re-run cmake configure.  It doesn't consider env vars as things to watch for change to cause a re-configure, which also causes no rebuild.  There does not appear to be a way to make CMake aware of env vars at all during its pre-check phase, and if it passes the pre-check phase, it does not even attempt to reconfigure at all.  
2. Even if you do reconfigure, CMake itself also caches things like paths to programs found, if using find_program() inside the cmake cache.

Maybe a custom build rule can be added that causes the build to fail if it detects this (you can read the value of env vars in cmake) but also writes a file to the build tree that contains the current set of env vars (ie, a file that contains "ROS_DISTRO=galactic") which is used to detect the new distro, during this custom build rule.  The file can be written/created during configure, and made a dependency of configure, so if it changes, it forces a reconfigure.  Then if the user switches the distro and runs the build, this custom pre-build step would detect the change, write the new file (ROS_DISTRO=humble) and error out saying "Please re-run the build, distro has changed".  If you do that, then the next time they try to run cmake build, it will rerun configure, since it would depend on that file.

Maybe something like that?

See Also:
Cmake property CONFIGURE_DEPENDS - used to add a file to the list of files that trigger auto-reconfigure before build.
Cmake ENV var query - you can get the value of an env var.
CMake file parsing - via json or plaintext, cmake can read a file during cmake script execution
CMake custom pre-build commands : add_custom_command(TARGET ... PRE_BUILD .. Command to run)
CMake script mode commands (you can tell Cmake to execute a cmake script as the custom build command)
