### ISSUE TITLE
Warehouse Project Template: provide instructions for ros2 navigation with a small fleet of robots.

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#184]
**Is your feature request related to a problem? Please describe.**
To help the user to quickly build a robotic simulation with the Warehouse Project Template, instructions on how to navigate the robots with ROS 2 should be included.

This could be a basis for tutorial.

**Describe the solution you'd like**
The documentation should refer to ROS 2 navigation stack and other relevant packages. If there is a common part between this and existing demo projects, it should be extracted to the ROS 2 Gem documentation under dedicated section, and only specifics included in documentation for the Template.

The instructions should come together with enough context for learning and a complete set of required commands, which are best to be provided as a dockerfile that the user can run. 

**Additional context**
This is a sub-task for the Warehouse Project Template. Relevant context: #180.

The instructions are to be extended with a chapter "How to scale up?", which will handle setup for distributed, cloud based setup for  fleets of robots.

**Comment by pijaro** [comment]
An important insight from the analysis of the fleet navigation with nav2 and o3de.

Nav2 generally expects the namespace of the TF to be handled via the different TF topics rather than adding namespaces to each frame:
- each robot should have separate TF topic - `/robot0/tf` `/robot0/tf_static` and so on,
- since the `tf2_ros::TransformBroadcaster`s don't support TF prefixing, it is required to remap global `/tf` frames into relative `tf` via the node arguments ([as it can be seen in the nav2 launchfiles](https://github.com/ros-planning/navigation2/blob/humble/nav2_bringup/launch/bringup_launch.py#L47-L54))
- it requires an introduction of per-robot nodes (currently there is one node handling everything)

It would be beneficial to reconsider the approach of how the frames' namespace is handled.  With the nav2 approach, we could utilize the Nav2 launch files directly with the o3de. It would be also very easy to modify the multi tb3 launchfile to get the fleet navigation example that we need.
