### ISSUE TITLE
problems with displaying meshes when importing UR10

### ISSUE THREAD

**Issue by lewandowskikacper** [o3de/o3de-extras#509]
When importing UR10 robot from https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/tree/ros2: 

`xacro src/Universal_Robots_ROS2_Description/urdf/ur.urdf.xacro name:=ur10 ur_type:=ur10 > ur10.urdf`

or with Robot Importer from `src/Universal_Robots_ROS2_Description/urdf/ur.urdf.xacro` with parameters set as above, 

some of the meshes are not displayed correctly, causing empty spaces to appear:
![image](https://github.com/o3de/o3de-extras/assets/138626322/ea1517d3-b562-4667-84c9-c6e2df380e70)

above,  the https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/blob/ros2/meshes/ur10/visual/shoulder.dae
is displayed incorrectly (only the top blue part is visible).

Other tools, such as blender can display the whole mesh:

![image](https://github.com/o3de/o3de-extras/assets/138626322/0c0a4b27-7cac-449a-9471-28c6c4bb174b)

After exporting this mesh as `stl` in blender, o3de can import it correctly as well:
![image](https://github.com/o3de/o3de-extras/assets/138626322/3a226871-e50a-4f12-b596-e86349d81b65)

**Comment by mbalfour-amzn** [comment]
FWIW, the reason for the missing mesh is that shape0 in the shoulder.dae file has a "lines" primitive, as well as triangles:
        <lines count="4">
          <input semantic="VERTEX" source="#shape0-mesh-vertices" offset="0"/>
          <p>19 681 685 3171 683 685 681 4326</p>
        </lines>

Currently, this causes the "AreAllMeshesValid()" check to fail in AssImpMeshImporter for this node, since our importer can only handle triangulated meshes, not lines, which is why it doesn't show up. It _might_ be possible to remove this check and simply skip the invalid faces with a warning instead of a complete failure.

**Comment by mbalfour-amzn** [comment]
I've posted a PR that skips the invalid faces, which makes this piece import correctly:
https://github.com/o3de/o3de/pull/16724

**Comment by mbalfour-amzn** [comment]
PR has been submitted, this bug should now be fixed.
